### ISSUE TITLE
Configuration for RDS encrpytion

### ISSUE THREAD

**Issue by jgdef-tulip** [EngineerBetter/control-tower#158]
Hi. Is there an option to create an RDS instance with encryption enabled?

There's an [old blog post](https://www.engineerbetter.com/blog/perpetual-motion-software-updates/) that says:
```
Concourse has the option to encrypt its database, but it isn’t enabled by default. Concourse-up now enables encryption of the Concourse DB. Run concourse-up info --json <YOUR DEPLOYMENT NAME> if you need to recover your DB encryption key.
```

As the successor project (?) to concourse-up, I hope this is still possible. Thanks.

**Comment by crsimmons** [comment]
Control Tower is basically a rename of Concourse-up that we continued developing so every feature of the latter should still be present in the former.

The encryption mentioned in that blog post is actually [a feature of Concourse](https://concourse-ci.org/encryption.html) rather than something we enable on the RDS instance itself. We enable this feature in Control Tower by default (in fact you can't opt out even if you wanted to).

You can see the option being defined [in the deployment manifest](https://github.com/EngineerBetter/control-tower-ops/blob/master/manifest.yml#L135). Also the part in the blog post about retrieving the key is still correct - if you run `control-tower info --json` for your deployment and look for `encryption_key`.
