### ISSUE TITLE
web node terminated with volume deleted in AWS. 

### ISSUE THREAD

**Issue by huiz-psma** [EngineerBetter/control-tower#171]
now redeploy is failing with the error message 

Creating missing vms: web/xxxxxxxxxx
Error: Unknown CPI error 'Unknown' with message 'The volume 'vol-xxxxxxxx' does not exist.' in 'create_vm' CPI method (CPI request ID: 'cpi-297816')

Is there any way to recreate the volume and get the web node created? Thank you in advance.

**Comment by crsimmons** [comment]
I don't recall seeing an error like that in Control Tower before. What were the circumstances around the web vm terminating (i.e. was it a self-update/control-tower deploy or some kind of IaaS issue)?

I think the default behaviour of BOSH is to dettach volumes rather than deleting them. Does the volume referenced in the error exist in AWS (EC2 -> Elastic Block Store -> Volumes)?

I'm not sure what data actually gets stored on disk in the web since most state ends up in RDS.

Assuming the volume is completely gone you might be able to get BOSH to fix itself by:

* Export creds with `eval "$(control-tower info --iaas AWS --env <deployment-name>)"`

then one of:

* `bosh cck` then follow the prompts to apply suggested fixes

or 

* `bosh deploy --fix --recreate --recreate-persistent-disks <(bosh manifest)`

**Comment by huiz-psma** [comment]
Thank you @crsimmons I ended up recreating the CI as I need it to progress codes. bookmarked this thread.

FYI, long story about the the original error. The bosh director kept recreating the web node. After the recreation, I did bosh vms and it returns two nodes running, one web and one worker. but a few hours later, I would see the web node getting terminated and recreated. When this happened, it would happen for 2 to 3 times continuous and be good for a few hours before the next round. I lost the logs, but the director was complaining about many components not responding, e.g. influxDB. Upgrade/ downgrade control tower only recreate the bosh instance. The error cycle continued. so I thought maybe the agent on the web node is the problem and deleted the volume hoping it would be recreated.

**Comment by huiz-psma** [comment]
Thanks @crsimmons  for the information. I wish this was available somewhere when I was troubleshooting. I believe it will be helpful for other users if the tools are documented. 

So far, the new CI is stable. we can close this issue. Cheers
