### ISSUE TITLE
Unable to build images with packer in concourse job

### ISSUE THREAD

**Issue by smgoller** [EngineerBetter/control-tower#18]
I've got a concourse pipeline that uses packer to build a windows instance. To connect to the windows instance, packer uses WinRM which utilizes TCP port 5986. Unfortunately, the container for the job isn't able to successfully connect to that port and just times out. The windows instance gets created in the default network, and I'm able to talk to it via winrm from outside the control-tower networks. I've tried adjusting the "control-tower-*-[private|public]" firewall rules to allow this port, but that doesn't seem to help. How can I adjust what ports concourse jobs are able to connect to?

**Comment by DanielJonesEB** [comment]
Hi @smgoller,

There shouldn't be any restrictions on egress traffic from Concourse workers. Which IAAS are you using? You could try using `eval "$(control-tower info  --iaas AWS --env name)"` and then use `bosh ssh -d concourse worker` to get a terminal session on the worker, and try debugging from there using `netcat` and the like.

**Comment by glend** [comment]
@DanielJonesEB just want to note that I've had issues with egress traffic firewall. I'm on the latest `concourse-up` version so I'm not sure if it still applies here, but I had to add a port in `concourse-up-xxx-private` firewall rule otherwise my jobs wouldn't connect to an external k8s cluster.

**Comment by smgoller** [comment]
This is on GCP. I've done a ton of debugging, and continue to do so. Is there a document that explains how you've set up the network architecture? Is there any special configuration of the NAT instance going on?

**Comment by DanielJonesEB** [comment]
Hi folks,

Apologies for the slow responses - we're all out on work with customers currently. Best place to check what network config is being applied is the Terraform file for GCP: https://github.com/EngineerBetter/control-tower/blob/master/resource/assets/gcp/infrastructure.tf

**Comment by glend** [comment]
I had to open up a port here https://github.com/EngineerBetter/control-tower/blob/master/resource/assets/gcp/infrastructure.tf#L256 otherwise it wouldn't work in GCP.

**Comment by crsimmons** [comment]
Ah right. This has tripped us up before. On GCP the NATing of the workers is done with a NAT vm in the private subnet. Since it's a VM it needs firewall rules to dictate what can reach it so effectively that rule becomes an egress firewall on the workers. It only happens on GCP since AWS uses a separate NAT gateway resource.

Off the top of my head I'm not sure what the security implication of just opening that firewall up entirely would be. We could also potentially add a flag for adding ports to that rule.

**Comment by portepa** [comment]
Hi,

Wanted to connect to the PKS API during a task within concourse, deployed via control-tower (v0.3.0) on GCP, had the same problem: unreachable service & timeout. Did not try on AWS but from my understanding of your comments, it should have worked fine.

Resolved it by adding port 9021 (PKS API port) on the NAT firewall rule, which is used here https://github.com/EngineerBetter/control-tower/blob/master/resource/assets/gcp/infrastructure.tf#L200

Adding ports via flags as mentioned by @crsimmons should help because I'm not sure adding port directly within the configuration file is the proper way to go, as everyone will have their own needs.

Happy to help if needed

**Comment by crsimmons** [comment]
Hi all. I've just cut [a new release](https://github.com/EngineerBetter/control-tower/releases/tag/0.7.0) which changes our implementation of worker NATing on GCP. The firewall rules should no longer impact egress traffic from the workers. Let us know if you have any further issues.
