### ISSUE TITLE
why can't I find my control-tower generated credentials in credhub

### ISSUE THREAD

**Issue by michaellihs** [EngineerBetter/control-tower#2]
First of all thanks a lot for your tooling - I tried it out yesterday on GCP and after a few issues concerning my lack of knowledge regarding GCP, it worked like a charm.

One thing I was wondering about was that I couldn't find my credentials (e.g. Concourse password) in credhub after spinning up the setup on GCP:

```
$ eval "$(control-tower info --region europe-west1  --iaas gcp --env concourse)"
$ credhub find
credentials: []
```

Is this the intended behavior? If yes, why don't you store all generated credentials of the BOSH deployment in credhub - or am I missing something?

Thanks in advance!

**Comment by DanielJonesEB** [comment]
Thanks for getting in touch @michaellihs. This is intentional behaviour - we see CredHub as something the _user_ utilises, rather than the tool. We also have a chicken-and-egg problem in that Control Tower needs some of those credentials in order to be able to access CredHub in the first place; if CredHub went down Control Tower would then be powerless to fix it in an update.

Instead we store credentials in an S3/GCS bucket, so all of the configuration we generate is in one place.

**Comment by michaellihs** [comment]
Maybe as a hint for other people who want their Concourse credentials in Credhub: #4 shows how it can be done :)
