### ISSUE TITLE
Scale worker instances according to build queue?

### ISSUE THREAD

**Issue by RichardBradley** [EngineerBetter/control-tower#40]
Is it possible to scale the number of workers according to the length of the build queue?

It seems wasteful to be paying for an m4.xlarge instance 24x7 when it is only used sporadically. 
Jenkins has this feature already.

Thanks,

Rich

**Comment by crsimmons** [comment]
As far as I know this is not a supported feature of Concourse. Without support in the underlying product I think it would be too complex for us to implement in Control Tower (especially since we would need to make it IaaS agnostic).

I do think this would be a useful feature. You could try raising a feature request directly with the [Concourse team](https://github.com/concourse/concourse).

This could also conceivably be accomplished with some kind of AWS Auto Scaling Group setup but this would require manual changes on your part that would likely prevent you from using Control Tower to manage your deployment going forward.

**Comment by DanielJonesEB** [comment]
Sadly auto-scaling was never added to BOSH: https://github.com/cloudfoundry/bosh/issues/1652

There was a third-party implementation that has since been removed from GitHub.

**Comment by crsimmons** [comment]
Closing this as it is not possible with Control Tower currently and implementation of such a feature is better suited for BOSH. Bump the GitHub issue mentioned by DJ above to let the BOSH team know it would be helpful.
