### ISSUE TITLE
self-update pipeline removes the allow-ips from the aws_security_group.atc

### ISSUE THREAD

**Issue by EnorMOZ** [EngineerBetter/control-tower#76]
Updated from 0.12.0 to 0.13.0:

When running the self-update pipeline it modifies the aws_security_group.atc. When doing so it will remove any allow-ips you set initially and adds 0.0.0.0. This is no bueno as it now opens it up to the world. 

[self-update-sg-output.txt](https://github.com/EngineerBetter/control-tower/files/5319968/self-update-sg-output.txt)

**Comment by EnorMOZ** [comment]
It looks like that param is not used at all during the self-update pipeline so it defaults to 0.0.0.0

**Comment by crsimmons** [comment]
I can reproduce this on 0.12.11 -> 0.13.0

The reason it happens is that [we intentionally overwrite allowed IPs with the ones provided as deploy args](https://github.com/EngineerBetter/control-tower/blob/master/concourse/config.go#L124-L134). It is implemented this way so that allowed IPs can be updated and/or removed with the same flag. The flaw as you've noticed is in self-update where the IPs would need to be provided at deploy time but the pipeline isn't written that way.

I'm working on two fixes:

1. clarify in the deploy docs that allow IPs must be specified on every manual deploy
1. passing currently-configured allow IPs to the self-update pipeline

**Comment by crsimmons** [comment]
I've just cut [0.13.1](https://github.com/EngineerBetter/control-tower/releases/tag/0.13.1) with a fix for this. You will need to update manually providing the `--allow-ips` flag but then subsequent self-updates will retain the allow list.
