### ISSUE TITLE
[Feature-Request] Don't re-run terraform on subsequent deploy command

### ISSUE THREAD

**Issue by EnorMOZ** [EngineerBetter/control-tower#80]
After a deploy is done you can only update specific aspects of the deploy. However if there were manual changes to route tables/security groups etc it gets overwritten on subsequent deploy commands. This could be a feature flag 🤷

**Comment by crsimmons** [comment]
I'm not sure how we would get this to work with updates. If we make a terraform change in a new version of Control Tower the terraform would need to run on the next deploy (whether that happens in the pipeline or manually) and would reset manual changes anyway.

In the past we've seen things like this as "the cost" of using an opinionated tool to deploy/manage Concourse. If you choose to use Control Tower you get an easier experience but you lose some of the control you would get if you deployed yourself. This approach lets us offer features like self-update because the starting point for an upgrade is more predictable. This is why we've shied away from allowing custom ops files. If you want fine-grained control and access to every possible option you will always be better off deploying Concourse yourself. Generally if a feature is missing from Control Tower we suggest one of two options:

1. PR the feature into Control Tower
1. Make the change manually then forfeit the ability to use Control Tower for subsequent upgrades

So from the perspective of your comment I'd be more open to PRs/feature requests to add the ability to provide custom route table or security group rules as flags on Control Tower itself.
